<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>fileTypes</key>
		<array>
			<string>s</string>
			<string>S</string>
			<string>asm</string>
			<string>ASM</string>
		</array>
		<key>name</key>
		<string>ca65</string>
		<key>patterns</key>
		<array>
			<dict>
				<key>match</key>
				<string>;.*$</string>
				<key>name</key>
				<string>comment.line</string>
			</dict>
			<dict>
				<key>match</key>
				<string>".*?"</string>
				<key>name</key>
				<string>string.quoted</string>
			</dict>
			<dict>
				<key>match</key>
				<string>#?\$[0-9a-fA-F]+</string>
				<key>name</key>
				<string>constant.numeric.hex</string>
			</dict>
			<dict>
				<key>match</key>
				<string>#?%[0-1]+\b</string>
				<key>name</key>
				<string>constant.numeric.other</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\#[0-9]+\b</string>
				<key>name</key>
				<string>constant.numeric.int</string>
			</dict>
			<dict>
				<key>match</key>
				<string>(?&lt;=\s|^)[@0-9a-zA-Z_-]+\:</string>
				<key>name</key>
				<string>entity.name.function</string>
			</dict>
			<dict>
				<key>match</key>
				<string>(?i)(\.(autoimport|import|export|segment|proc|a8|a16|i16|endproc|include|macro|endmacro|asciiz|word|byte|incbin|loword))\b(?-i)</string>
				<key>name</key>
				<string>support.function</string>
			</dict>
			<dict>
				<key>match</key>
				<string>(?i)(?&lt;=\s|^)(ADC|AND|BCC|BCS|BEQ|BIT|BMI|BNE|BPL|BRA|BRK|BVC|BVS|CLC|CLD|CLI|CLP|CLR|CMP|CPX|CPY|CSP|DEC|DEX|DEY|EOR|HLT|INC|INX|INY|JML|JMP|JSR|LDA|LDX|LDY|MVN|MVP|NOP|ORA|PHA|PHB|PHD|PHK|PHP|PHX|PHY|PLA|PLB|PLD||PLP|PLX|PLY|PSH|PUL|RET|ROL|ROR|RTI|RTL|RTS|SBC|SEC|SED|SEI|SEP|SHL|SHR|STA|STX|STY|STZ|SWA|TAD|TAS|TAX|TAY|TCB|TDA|TSA|TSB|TSX|TXA|TXS|TXY|TYA|TYX|WAI|XCE)\b(?-i)</string>
				<key>name</key>
				<string>keyword.operator.word</string>
			</dict>
		</array>
		<key>scopeName</key>
		<string>source.ca65</string>
	</dict>
</plist>