<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>fileTypes</key>
		<array>
			<string>s</string>
			<string>S</string>
			<string>asm</string>
			<string>ASM</string>
		</array>
		<key>name</key>
		<string>ca65</string>
		<key>patterns</key>
		<array>
			<dict>
				<key>match</key>
				<string>;.*$</string>
				<key>name</key>
				<string>comment.line</string>
			</dict>
			<dict>
				<key>match</key>
				<string>".*?"</string>
				<key>name</key>
				<string>string.quoted</string>
			</dict>
			<dict>
				<key>match</key>
				<string>#?\$[0-9a-fA-F]+</string>
				<key>name</key>
				<string>storage.type</string>
			</dict>
			<dict>
				<key>match</key>
				<string>#?\%[0-9a-fA-F]+\b</string>
				<key>name</key>
				<string>storage.type</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\#[0-9a-zA-Z]+\b</string>
				<key>name</key>
				<string>storage.type</string>
			</dict>
			<dict>
				<key>match</key>
				<string>^[@0-9a-zA-Z]+\b\:</string>
				<key>name</key>
				<string>entity.name.function</string>
			</dict>
			<dict>
				<key>match</key>
				<string>[\s]+[.]{1}[a-zA-Z]+\b</string>
				<key>name</key>
				<string>constant.language</string>
			</dict>
			<dict>
				<key>match</key>
				<string>^(?i)(?=(\s*|$))(\.(autoimport|import|export|segment|proc|a8|a16|i16|endproc))(?-i)</string>
				<key>name</key>
				<string>keyword.control</string>
			</dict>
			<dict>
				<key>match</key>
				<string>(?i)(?&lt;=\s)(ADC|AND|ASL|BCC|BCS|BEQ|BIT|BMI|BNE|BPL|BRK|BVC|BVS|CLC|CLD|CLI|CLV|CMP|CPX|CPY|DEC|DEX|DEY|EOR|INC|INX|INY|JMP|JSR|LDA|LDX|LDY|LSR|NOP|ORA|PHA|PHP|PLA|PLP|ROL|ROR|RTI|RTS|SBC|SEC|SED|SEI|STA|STX|STY|TAX|TAY|TSX|TXA|TXS|TYA|STZ|REP|SEP|XCE|PHK|PLB)(?=(\s|$))(?-i)</string>
				<key>name</key>
				<string>keyword.operator</string>
			</dict>
		</array>
		<key>scopeName</key>
		<string>source.ca65</string>
	</dict>
</plist>